server:
  port : 8092
  servlet:
    context-path: /sm-library
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
spring:
    profiles.active: localdev
---
spring:
  config:
    activate:
      on-profile: localdev
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans : true
      event:
          merge:
            entity_copy_observer: allow
    show-sql: true  
    properties:
      hibernate.format_sql: true

#springdoc.show-actuator: true
  
#springdoc.use-management-port: true
#management.endpoints.web.exposure.include: openapi, swagger-ui
#management.server.port: 8092

---
---
spring:
  config:
    activate:
      on-profile: test    
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans : true
      event:
          merge:
            entity_copy_observer: allow
    show-sql: true  
    properties:
      hibernate.format_sql: true