server:
  port: 8092
  servlet:
    context-path: /sm-library
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smaster
    username: smaster
    password: smaster
  jpa:
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans : true
      event:
          merge:
            entity_copy_observer: allow
    show-sql: true  
    properties:
      hibernate.format_sql: true

#springdoc.show-actuator: true
  
#springdoc.use-management-port: true
#management.endpoints.web.exposure.include: openapi, swagger-ui
#management.server.port: 8092